stages:
  split_data:
    cmd: python src/data/stratification.py --config data/data_config.yaml 
      --annotation-path data/annotations/annotations-coco-1.0.json --output-dir 
      data/interim
    deps:
    - data/annotations/annotations-coco-1.0.json
    - src/data/augmentation.py
    - src/data/stratification.py
    params:
    - data/data_config.yaml:
      - augmentation.motion_blur
      - augmentation.prefix
      - augmentation.random_brightness_contrast
      - augmentation.shift_scale_rotate
      - augmentation.strategies
      - split.min_instances
      - split.seed
      - split.test_ratio
      - split.train_ratio
      - split.val_ratio
      - stratification.r_env
      - stratification.r_geo
    outs:
    - data/interim/augmented_images
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
  convert_detection:
    cmd: python src/data/coco_to_yolo.py --task detection --input data/interim 
      --output data/processed/detection --category-id 1 --category-name 
      container_door --config data/data_config.yaml
    deps:
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
    - src/data/coco_to_yolo.py
    params:
    - data/data_config.yaml:
      - detection.category_id
      - detection.category_name
    outs:
    - data/processed/detection
  convert_localization:
    cmd: python scripts/data_processing/prepare_module_3_data.py --input 
      data/interim --output data/processed/localization --images-dir data/raw 
      --config data/data_config.yaml
    deps:
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
    - data/raw
    - scripts/data_processing/prepare_module_3_data.py
    params:
    - data/data_config.yaml:
      - localization.cont_id_category_id
      - localization.cont_id_category_name
      - localization.num_keypoints
      - localization.cont_door_category_id
      - localization.cont_door_category_name
      - localization.min_crop_size
    outs:
    - data/processed/localization

# ============================================================================
# TRAINING STAGES REMOVED
# ============================================================================
# Training is now executed as standalone scripts (NOT DVC stages)
# Rationale:
#   1. Separation of Concerns: Data pipeline vs Training
#   2. Multi-environment: Training can run on local/Kaggle/cloud
#   3. Experiment Tracking: WandB handles metrics/plots
#   4. Simplicity: No dependency chain validation issues
#
# To train detection model:
#   python src/detection/train_and_evaluate.py --config experiments/001_det_baseline.yaml
#
# Model versioning (manual):
#   dvc add artifacts/detection/.../train/weights/best.pt
#   git add artifacts/detection/.../train/weights/best.pt.dvc
#   git commit -m "feat(model): trained YOLOv11s baseline"
