stages:
  split_data:
    cmd: python src/data/stratification.py --config data/data_config.yaml 
      --annotation-path data/annotations/annotations-coco-1.0.json --output-dir 
      data/interim
    deps:
    - data/annotations/annotations-coco-1.0.json
    - src/data/augmentation.py
    - src/data/stratification.py
    params:
    - data/data_config.yaml:
      - augmentation.motion_blur
      - augmentation.prefix
      - augmentation.random_brightness_contrast
      - augmentation.shift_scale_rotate
      - augmentation.strategies
      - split.min_instances
      - split.seed
      - split.test_ratio
      - split.train_ratio
      - split.val_ratio
      - stratification.r_env
      - stratification.r_geo
    outs:
    - data/interim/augmented_images
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
  convert_detection:
    cmd: python src/data/coco_to_yolo.py --task detection --input data/interim 
      --output data/processed/detection --category-id 1 --category-name 
      container_door --config data/data_config.yaml
    deps:
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
    - src/data/coco_to_yolo.py
    params:
    - data/data_config.yaml:
      - detection.category_id
      - detection.category_name
    outs:
    - data/processed/detection
  convert_localization:
    cmd: python src/data/coco_to_yolo.py --task pose --input data/interim 
      --output data/processed/localization --category-id 2 --category-name 
      container_id --config data/data_config.yaml
    deps:
    - data/interim/test_master.json
    - data/interim/train_master.json
    - data/interim/val_master.json
    - src/data/coco_to_yolo.py
    params:
    - data/data_config.yaml:
      - localization.category_id
      - localization.category_name
      - localization.num_keypoints
    outs:
    - data/processed/localization
  train_detection:
    cmd: python src/detection/train_and_evaluate.py --config experiments/001_det_baseline.yaml 
      --experiment detection_exp001_yolo11s_baseline
    deps:
    - data/processed/detection
    - src/detection/train_and_evaluate.py
    - experiments/001_det_baseline.yaml
    params:
    - experiments/001_det_baseline.yaml:
      - detection
    outs:
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/weights/best.pt
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/weights/last.pt
    - artifacts/detection/detection_exp001_yolo11s_baseline/test
    metrics:
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/metrics.json:
        cache: false
    plots:
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/results.csv:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/confusion_matrix.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/F1_curve.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/PR_curve.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/P_curve.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/R_curve.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/train/results.png:
        cache: false
    - artifacts/detection/detection_exp001_yolo11s_baseline/test/confusion_matrix.png:
        cache: false
